# Generated by Django 5.0.4 on 2024-04-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contacts_contact_contacts_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': ' Контакты'},
        ),
    ]
