# Generated by Django 5.0.4 on 2024-04-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contacts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Почта '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='our_location',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
