# Generated by Django 5.0.4 on 2024-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contacts_email_contacts_our_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email1',
            field=models.EmailField(default=1, max_length=255, verbose_name='Почта '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number1',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number2',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number3',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона 2'),
            preserve_default=False,
        ),
    ]
