# Generated by Django 5.0.4 on 2024-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_contacts_phone_number3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона 1'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number1',
            field=models.CharField(max_length=255, verbose_name='Номер телефона 2'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number2',
            field=models.CharField(max_length=255, verbose_name='Номер телефона 3'),
        ),
    ]
