# Generated by Django 5.0.4 on 2024-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contacts_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number1',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number2',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона '),
        ),
    ]
