# Generated by Django 5.0.4 on 2024-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': ' Курсы'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса'),
            preserve_default=False,
        ),
    ]
