# Generated by Django 5.0.4 on 2024-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_course_options_course_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='course1',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='course_title1',
        ),
        migrations.AddField(
            model_name='course',
            name='course2',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course3',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course4',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course5',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course6',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title2',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title3',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title4',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title5',
            field=models.CharField(default=111, max_length=255, verbose_name='заголовка курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_titles6',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса'),
            preserve_default=False,
        ),
    ]
