# Generated by Django 5.0.4 on 2024-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_rename_course_course_course1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course1',
            field=models.CharField(max_length=255, verbose_name='курс 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course2',
            field=models.CharField(max_length=255, verbose_name='курс 2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course3',
            field=models.CharField(max_length=255, verbose_name='курсы 3'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course4',
            field=models.CharField(max_length=255, verbose_name='курсы 4'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course5',
            field=models.CharField(max_length=255, verbose_name='курсы 5'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course6',
            field=models.CharField(max_length=255, verbose_name='курсы 6'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title1',
            field=models.CharField(max_length=255, verbose_name='заголовка курса 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title2',
            field=models.CharField(max_length=255, verbose_name='заголовка курса 2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title3',
            field=models.CharField(max_length=255, verbose_name='заголовка курса 3'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title4',
            field=models.CharField(max_length=255, verbose_name='заголовка курса 4'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title5',
            field=models.CharField(max_length=255, verbose_name='заголовка курса 5'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_titles6',
            field=models.CharField(max_length=255, verbose_name='заголовка курса 6'),
        ),
    ]
