# Generated by Django 5.0.4 on 2024-04-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_alter_course_course1_alter_course_course2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image1',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image2',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image3',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image4',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image5',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image6',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса'),
            preserve_default=False,
        ),
    ]