# Generated by Django 5.0.4 on 2024-04-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_alter_course_image1_alter_course_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course6',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_titles6',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image6',
        ),
        migrations.AlterField(
            model_name='course',
            name='course1',
            field=models.CharField(max_length=255, verbose_name='курс '),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title1',
            field=models.CharField(max_length=255, verbose_name='заголовка курса '),
        ),
        migrations.AlterField(
            model_name='course',
            name='image1',
            field=models.ImageField(upload_to='info_user/', verbose_name='Фотография курса'),
        ),
    ]
