# Generated by Django 5.0.4 on 2024-04-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_remove_course_course2_remove_course_course3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course2',
            field=models.CharField(default=1, max_length=255, verbose_name='курс 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course3',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course4',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course5',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course6',
            field=models.CharField(default=1, max_length=255, verbose_name='курсы 6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title2',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title3',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title4',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_title5',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_titles6',
            field=models.CharField(default=1, max_length=255, verbose_name='заголовка курса 6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image2',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image3',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image4',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image5',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image6',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография курса 6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course1',
            field=models.CharField(max_length=255, verbose_name='курс 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title1',
            field=models.CharField(max_length=255, verbose_name='заголовка курса 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image1',
            field=models.ImageField(upload_to='info_user/', verbose_name='Фотография курса 1'),
        ),
    ]
