# Generated by Django 5.0.4 on 2024-04-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_course_course2_course_course3_course_course4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price1',
            field=models.IntegerField(default=1, verbose_name='Цена курса 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price2',
            field=models.IntegerField(default=1, verbose_name='Цена курса 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price3',
            field=models.IntegerField(default=1, verbose_name='Цена курса 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price4',
            field=models.IntegerField(default=11, verbose_name='Цена курса 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price5',
            field=models.IntegerField(default=1, verbose_name='Цена курса 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price6',
            field=models.IntegerField(default=1, verbose_name='Цена курса 6'),
            preserve_default=False,
        ),
    ]
