# Generated by Django 5.0.4 on 2024-04-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_course_price1_course_price2_course_price3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course6',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_title5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_titles6',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price6',
        ),
    ]
