# Generated by Django 5.0.4 on 2024-04-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_remove_course_course2_remove_course_course3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course1',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_title1',
            new_name='course_title',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price1',
            new_name='price',
        ),
    ]
