# Generated by Django 5.0.4 on 2024-04-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('secondary', '0011_rename_course1_course_course_and_more'),
    ('secondary', '0013_alter_course_course_alter_course_course_title_and_more'),
]


    operations = [
    ]
