# Generated by Django 5.0.4 on 2024-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_course', models.CharField(max_length=255, verbose_name='Когда обучался')),
                ('where_study', models.CharField(max_length=255, verbose_name='Где учился')),
                ('course_name', models.CharField(max_length=255, verbose_name='В каком курсе или университе училя')),
            ],
            options={
                'verbose_name': 'Мое оброзование',
                'verbose_name_plural': 'Мое оброзование',
            },
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='info_user/', verbose_name='Фотография пользователя')),
                ('work', models.CharField(max_length=255, verbose_name='Профессия пользователя')),
                ('skills', models.CharField(max_length=255, verbose_name='Каким образом пользователь делает работу')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта пользователя')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователя',
            },
        ),
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_job', models.CharField(max_length=255, verbose_name='Тип работы')),
                ('number_service', models.IntegerField(verbose_name='Номер работы (порядок)')),
                ('aboutproj', models.CharField(max_length=255, verbose_name='Коротко как я делает роботу')),
            ],
            options={
                'verbose_name': 'Мои услуги',
                'verbose_name_plural': 'Мои услуги',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typedevelop', models.CharField(max_length=255, verbose_name='Какой разработчик')),
                ('time', models.CharField(max_length=255, verbose_name='В каком году начал и закончил')),
                ('location', models.CharField(max_length=255, verbose_name='Где работал')),
            ],
            options={
                'verbose_name': 'Мой опыт',
                'verbose_name_plural': 'Мой опыт',
            },
        ),
    ]
