# Generated by Django 5.0.4 on 2024-04-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='InfoUser',
        ),
        migrations.DeleteModel(
            name='MyService',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
