# Generated by Django 5.0.4 on 2024-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_delete_education_delete_infouser_delete_myservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_users/', verbose_name='Фотография руководителя')),
                ('name', models.CharField(max_length=255, verbose_name='заголовок сайта')),
                ('discription', models.CharField(max_length=255, verbose_name='Описания')),
            ],
            options={
                'verbose_name': 'Главная страница сайта ',
                'verbose_name_plural': ' Главная страницы сайта',
            },
        ),
    ]
