# Generated by Django 5.0.4 on 2024-04-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
