# Generated by Django 5.0.4 on 2024-04-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=255, verbose_name='Главная страница')),
                ('image', models.ImageField(upload_to='info_users/', verbose_name='Фотография  загловка')),
                ('discription', models.TextField(max_length=255, verbose_name='описания заговка')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': ' Главная страницы',
            },
        ),
    ]
