# Generated by Django 5.0.4 on 2024-04-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='home',
            new_name='name',
        ),
    ]
