# Generated by Django 5.0.4 on 2024-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_home_home_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=255, verbose_name='О нас')),
                ('name', models.CharField(default='Введите Ф.И.О рукаводителя ', max_length=255, verbose_name='Ф.И.О')),
                ('image', models.ImageField(upload_to='info_user/', verbose_name='Фотография руководителя')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта руководителя')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': ' О нас',
            },
        ),
    ]
