# Generated by Django 5.0.4 on 2024-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.CharField(max_length=255, verbose_name='Наш онлайн-курс')),
                ('yearsexper', models.IntegerField(verbose_name='Академические программы')),
                ('projectfinish', models.IntegerField(verbose_name='Сертифицированные студенты')),
                ('happyclients', models.IntegerField(verbose_name='Зачисленные студенты')),
            ],
            options={
                'verbose_name': 'Доп информации',
                'verbose_name_plural': 'Доп информации',
            },
        ),
    ]
