# Generated by Django 5.0.4 on 2024-04-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary',
            name='online',
            field=models.IntegerField(verbose_name='Наш онлайн-курс'),
        ),
    ]
