# Generated by Django 5.0.4 on 2024-04-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_secondary_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondary',
            old_name='yearsexper',
            new_name='Academic_programs',
        ),
        migrations.RenameField(
            model_name='secondary',
            old_name='projectfinish',
            new_name='Certified_Students',
        ),
        migrations.RenameField(
            model_name='secondary',
            old_name='happyclients',
            new_name='Enrolled_Students',
        ),
    ]
