# Generated by Django 5.0.4 on 2024-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_yearsexper_secondary_academic_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondary',
            name='image',
            field=models.ImageField(default=1, upload_to='info_users', verbose_name='Фотография  загловка'),
            preserve_default=False,
        ),
    ]
