# Generated by Django 5.0.4 on 2024-04-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_secondary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondary',
            name='image',
        ),
    ]
