# Generated by Django 5.0.4 on 2024-04-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_secondary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondary',
            name='image',
            field=models.ImageField(default=1, upload_to='info_user/', verbose_name='Фотография руководителя'),
            preserve_default=False,
        ),
    ]
