# Generated by Django 5.0.4 on 2024-04-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_secondary_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_user1/', verbose_name='Фотография Описание')),
                ('discription', models.TextField(verbose_name='описания')),
                ('discriptions', models.TextField(verbose_name='описания заговка 1')),
                ('discriptions1', models.TextField(verbose_name='описания заговка 2')),
            ],
            options={
                'verbose_name': 'Описания  курсов',
                'verbose_name_plural': ' Описания курсов',
            },
        ),
    ]
