# Generated by Django 5.0.4 on 2024-04-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_hom_discriptions1'),
    ]

    operations = [
        migrations.AddField(
            model_name='hom',
            name='discriptions1',
            field=models.CharField(default=1, max_length=255, verbose_name='короткое описания 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hom',
            name='discriptions3',
            field=models.CharField(default=1, max_length=255, verbose_name='короткое описания 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hom',
            name='discriptions',
            field=models.CharField(max_length=255, verbose_name='короткое описания 2'),
        ),
    ]
