# Generated by Django 5.0.4 on 2024-04-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_hom_discriptions1_hom_discriptions3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hom',
            name='discriptions2',
            field=models.CharField(default=1, max_length=255, verbose_name='короткое описания 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hom',
            name='discriptions',
            field=models.TextField(verbose_name='описания заговка 1'),
        ),
    ]
