# Generated by Django 5.0.4 on 2024-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_hom_discriptions2_alter_hom_discriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='the_background',
            field=models.ImageField(default=1, upload_to='info_users', verbose_name='Задний Фон'),
            preserve_default=False,
        ),
    ]
