# Generated by Django 5.0.4 on 2024-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_home_the_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary',
            name='image',
            field=models.ImageField(upload_to='info_user/', verbose_name='Фото заднего фона '),
        ),
    ]
